# Generated by Django 2.1.7 on 2019-02-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_price', models.IntegerField(null=True)),
                ('home_room', models.IntegerField(null=True)),
                ('home_address', models.CharField(max_length=50)),
                ('home_description', models.TextField()),
                ('home_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Type.HouseType')),
            ],
        ),
    ]
