# Generated by Django 2.1.7 on 2019-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
